[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { 
  NODE_ENV = "production", 
  LOG_LEVEL = "INFO",
  WORKERS = "2",
  MAX_WORKERS = "4"
}

[environments.staging]
variables = { 
  NODE_ENV = "staging", 
  LOG_LEVEL = "DEBUG",
  WORKERS = "1"
}

# Service configuration
[[services]]
name = "reddit-content-platform-api"
source = "."

[[services]]
name = "reddit-content-platform-worker"
source = "."
startCommand = "celery -A app.core.celery_app worker --loglevel=info --concurrency=2"

[[services]]
name = "reddit-content-platform-scheduler"
source = "."
startCommand = "celery -A app.core.celery_app beat --loglevel=info"