"""Add crawling job management tables

Revision ID: f2157b61b25f
Revises: 002
Create Date: 2025-07-24 10:33:43.754941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2157b61b25f'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_cache',
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_cache_cache_key'), 'metrics_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_metrics_cache_id'), 'metrics_cache', ['id'], unique=False)
    op.create_table('generated_content',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_used', sa.String(length=100), nullable=True),
    sa.Column('source_keywords', sa.Text(), nullable=True),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_id'), 'generated_content', ['id'], unique=False)
    op.create_table('process_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_logs_id'), 'process_logs', ['id'], unique=False)
    op.create_table('crawling_schedules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.Enum('ONCE', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='schedulefrequency'), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('job_parameters', sa.JSON(), nullable=True),
    sa.Column('job_priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='jobpriority'), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('successful_runs', sa.Integer(), nullable=True),
    sa.Column('failed_runs', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawling_schedules_id'), 'crawling_schedules', ['id'], unique=False)
    op.create_table('crawling_jobs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='jobpriority'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('queue_name', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_saved', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('points_consumed', sa.Integer(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['crawling_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawling_jobs_celery_task_id'), 'crawling_jobs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_crawling_jobs_id'), 'crawling_jobs', ['id'], unique=False)
    op.create_table('job_metrics',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('network_io', sa.Float(), nullable=True),
    sa.Column('disk_io', sa.Float(), nullable=True),
    sa.Column('items_per_second', sa.Float(), nullable=True),
    sa.Column('queue_size', sa.Integer(), nullable=True),
    sa.Column('active_connections', sa.Integer(), nullable=True),
    sa.Column('custom_metrics', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['crawling_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_metrics_id'), 'job_metrics', ['id'], unique=False)
    op.create_table('job_notifications',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['crawling_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_notifications_id'), 'job_notifications', ['id'], unique=False)
    op.drop_index('ix_point_transactions_operation_created', table_name='point_transactions')
    op.drop_index('ix_point_transactions_type_created', table_name='point_transactions')
    op.drop_index('ix_point_transactions_user_billing_created', table_name='point_transactions')
    op.drop_index('ix_usage_history_date_period', table_name='usage_history')
    op.drop_index('ix_usage_history_user_billing_date', table_name='usage_history')
    op.drop_index('uq_usage_history_user_date_period', table_name='usage_history')
    op.drop_index('ix_user_billing_user_id', table_name='user_billing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_billing_user_id', 'user_billing', ['user_id'], unique=1)
    op.create_index('uq_usage_history_user_date_period', 'usage_history', ['user_billing_id', 'date', 'period_type'], unique=1)
    op.create_index('ix_usage_history_user_billing_date', 'usage_history', ['user_billing_id', 'date'], unique=False)
    op.create_index('ix_usage_history_date_period', 'usage_history', ['date', 'period_type'], unique=False)
    op.create_index('ix_point_transactions_user_billing_created', 'point_transactions', ['user_billing_id', 'created_at'], unique=False)
    op.create_index('ix_point_transactions_type_created', 'point_transactions', ['transaction_type', 'created_at'], unique=False)
    op.create_index('ix_point_transactions_operation_created', 'point_transactions', ['operation_type', 'created_at'], unique=False)
    op.drop_index(op.f('ix_job_notifications_id'), table_name='job_notifications')
    op.drop_table('job_notifications')
    op.drop_index(op.f('ix_job_metrics_id'), table_name='job_metrics')
    op.drop_table('job_metrics')
    op.drop_index(op.f('ix_crawling_jobs_id'), table_name='crawling_jobs')
    op.drop_index(op.f('ix_crawling_jobs_celery_task_id'), table_name='crawling_jobs')
    op.drop_table('crawling_jobs')
    op.drop_index(op.f('ix_crawling_schedules_id'), table_name='crawling_schedules')
    op.drop_table('crawling_schedules')
    op.drop_index(op.f('ix_process_logs_id'), table_name='process_logs')
    op.drop_table('process_logs')
    op.drop_index(op.f('ix_generated_content_id'), table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index(op.f('ix_metrics_cache_id'), table_name='metrics_cache')
    op.drop_index(op.f('ix_metrics_cache_cache_key'), table_name='metrics_cache')
    op.drop_table('metrics_cache')
    # ### end Alembic commands ###
